version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: daily
    default_reviewers:
      - ollynevard
    commit_message:
      prefix: chore
      include_scope: true
