name: Validate Pull Request

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Build events
        uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.HONEYCOMB_API_KEY}}
          dataset: gha-build-events
          job-status: ${{ job.status }}

      - run: |
          echo ::set-env name=STEP_ID::0
          echo ::set-env name=STEP_START::$(date +%s)
      - name: Checkout codebase
        uses: actions/checkout@v2
      - run: buildevents step $TRACE_ID $STEP_ID $STEP_START 'checkout_codebase'

      - run: |
          echo ::set-env name=STEP_ID::1
          echo ::set-env name=STEP_START::$(date +%s)
      - name: Setup node
        uses: actions/setup-node@v1
      - run: buildevents step $TRACE_ID $STEP_ID $STEP_START 'setup_node'

      - run: |
          echo ::set-env name=STEP_ID::2
          echo ::set-env name=STEP_START::$(date +%s)
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - run: buildevents step $TRACE_ID $STEP_ID $STEP_START 'install_dependencies'

      - run: |
          echo ::set-env name=STEP_ID::3
          echo ::set-env name=STEP_START::$(date +%s)
      - name: Run linter
        run: buildevents cmd $TRACE_ID $STEP_ID lint -- npm run lint
      - run: buildevents step $TRACE_ID $STEP_ID $STEP_START 'run_linter'

